### ISSUE TITLE
Line 939 - Filter to N>=10?

### ISSUE THREAD

**Issue by mcsiple** [cstawitz/codloins#3]
This line filters all the data to Label-True combinations that have N>=10, but I'm not sure if this is what we did in the final analysis or why we did it for the figure. This reduces the dataframe from 2034 rows to 132, and 204 genera to 41. 

I think N is the number of samples in the study with that label... do you remember why we subsetted at this point?

**Comment by cstawitz** [comment]
I meant for this to filter out Genera which have fewer than 10 samples a.la line 156-157 of the text: "For each of these analyses, we calculated summary statistics for genera that had more than 10 unique fish products."

I think this line of code should apply AFTER the group by Genus a few lines down.

**Comment by mcsiple** [comment]
Ah, okay-- so in the code, this would be subsetting to tot >= 10, since tot = sum(N). Correct me if I'm wrong! new fig coming soon. I think it will have a lot more genera in it with this new condition-- which is cool.
