### ISSUE TITLE
Line 823 in Simulation.R: Getting only tiny values when bootstrapping IUCN diffs

### ISSUE THREAD

**Issue by mcsiple** [cstawitz/codloins#4]
Hi xtine,
I am attempting to re-calculate the bootstrapped IUCN difference, using our dataset with minor corrections (e.g., changing Salmo sp. to Salmo salar in a few samples) and with a new dataset that assigns poor statuses to DD/not evaluated species. For some reason I'm only getting tiny values (0 or some very small decimal (e.g., 4e-5) for the resampled data, even with n=1000 resamples. Am I missing something? The data.tbl I'm using is DataPricesStatuses_mcs_v2.csv, with numeric true & label statuses. I'm wondering if I'm doing something wrong, as even the original dataset is giving me tiny resampled differences.  Thanks!

**Comment by cstawitz** [comment]
Hi! Did you change the code at all? Or just the data?

**Comment by mcsiple** [comment]
Just the data. I haven't been changing anything that's on github-- I don't know if I'm able to push to codloins. I have been fiddling with the code but those are in files marked _mcs on Dropbox.

**Comment by mcsiple** [comment]
Oh! And if you run anything that uses DataFixed9, you should use DataFixed9_mcs_v2 -- I replaced several Atlantic salmon samples, originally "Salmo sp" with "Salmo salar" (after double checking w raw data from those papers)

**Comment by cstawitz** [comment]
OK it's running now - I'll see what I get.

One very confusing thing about the code is that you have to run lines 883-903 first, even though they come afterwards. But when I didn't do that I got an error, not tiny values..

**Comment by mcsiple** [comment]
Ah, I didn't see that at first, and wrote those couple lines on my own to get the numeric statuses. Now I'm getting things close to -1... I can't remember if we subsetted to mislabeled samples? Either way, let me know what you get when you re-run it so I can see if I did it right.
The steps I did were:
- Lookup statuses of labels and true
- assign IUCN status to all species using the lookup table
- assign mean IUCN status (genus mean) to samples with genus name only
- get numeric statuses of labels and true
- run bootstrappy code (lines 820-861)

**Comment by mcsiple** [comment]
OK upon re-running with your code I got something like 
      2.5%        50%      97.5% 
0.01992152 0.03923432 0.06164737 

Does that look similar to what you got? It won't be exactly the same because I used a slightly edited data file.

**Comment by cstawitz** [comment]
Yup that looks correct! So that would mean on average (median) actual substituted items are 3.92% of an IUCN status better than labeled items, with a range of 1.99% - 6.16% - reassuringly very close to what we had in the first place!!

**Comment by mcsiple** [comment]
YAAAAAAAAS!
